fail tests when -Wmaybe-uninitialized is triggered
This should prevent instances of bugs like that fixed in the previous commit
being reintroduced. Note that we need to skip this for `murphi2c` testing
because for a single test case, tests/smt-shadowed-decl.m, it actually warns
about a real problem in the model definition.

Github: #277 “'-Wmaybe-uninitialized' warnings”

diff --git a/tests/config/C_FLAGS b/tests/config/C_FLAGS
--- a/tests/config/C_FLAGS
+++ b/tests/config/C_FLAGS
@@ -16,6 +16,16 @@ if [ $? -eq 0 ]; then
   printf ', "-Werror=enum-conversion"'
 fi
 
+# test if the C compiler supports -Werror=maybe-uninitialized
+${CC:-cc} -x c -std=c11 -Werror=maybe-uninitialized -o /dev/null - &>/dev/null <<EOT
+int main(void) {
+  return 0;
+}
+EOT
+if [ $? -eq 0 ]; then
+  printf ', "-Werror=maybe-uninitialized"'
+fi
+
 # test if the C compiler supports -march=native
 ${CC:-cc} -x c -std=c11 -march=native -o /dev/null - &>/dev/null <<EOT
 int main(void) {
